baseURL = 'https://ronnyf.github.io/ios-eng'
languageCode = 'en-us'
title = 'iOS Engineering'
theme = 'github.com/adityatelange/hugo-PaperMod'
publishDir = 'public'

[params]
  # color style
  color = 'linen' # linen, wheat, gray, light

  # home page profile
  avatar = 'GRAVATAR_EMAIL' # gravatar email or image url
  name = 'RonnyF'
  bio = 'iOS Engineer'

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'layouts'
  target = 'layouts'
[[module.mounts]]
  source = 'data'
  target = 'data'
[[module.mounts]]
  source = 'assets'
  target = 'assets'
[[module.mounts]]
  source = 'i18n'
  target = 'i18n'
[[module.mounts]]
  source = 'archetypes'
  target = 'archetypes'
[[module.imports]]
  disable = false
  path = 'github.com/hugomods/search'
[[module.imports]]
  disable = false
  path = 'github.com/hugomods/images'
